package event

const (
	RunCreated              = "run.created"
	RunStarted              = "run.started"
	RunCompleted            = "run.completed"
	RunFailed               = "run.failed"
	WaveStarted             = "wave.started"
	WaveBarrierStarted      = "wave.barrier_started"
	WaveVerified            = "wave.verified"
	WaveBlocked             = "wave.blocked"
	SessionStarting         = "session.starting"
	SessionStarted          = "session.started"
	SessionResumed          = "session.resumed"
	ProcessSpawned          = "process.spawned"
	ProcessExited           = "process.exited"
	ProcessOrphaned         = "process.orphaned"
	SessionTerminated       = "session.terminated"
	TurnStarted             = "turn.started"
	ModelOutputDelta        = "model.output_delta"
	ModelMessageCompleted   = "model.message_completed"
	TurnCompleted           = "turn.completed"
	TurnFailed              = "turn.failed"
	TurnInterrupted         = "turn.interrupted"
	APIRetrying             = "api.retrying"
	ToolStarted             = "tool.started"
	ToolOutput              = "tool.output"
	ToolCompleted           = "tool.completed"
	ToolFailed              = "tool.failed"
	FileRead                = "file.read"
	FileChanged             = "file.changed"
	FileCreated             = "file.created"
	FileDeleted             = "file.deleted"
	UserInputRequested      = "user_input.requested"
	PermissionRequested     = "permission.requested"
	PermissionResolved      = "permission.resolved"
	ScopeExpansionRequested = "scope_expansion.requested"
	ScopeExpansionResolved  = "scope_expansion.resolved"
	ResultSubmitted         = "result.submitted"
	ResultValidationFailed  = "result.validation_failed"
	ReportPublished         = "report.published"
	QuestionPublished       = "question.published"
	TaskReportedComplete    = "task.reported_complete"
	TaskVerifiedSuccess     = "task.verified_success"
	TaskVerificationFailed  = "task.verification_failed"

	// Replayable state transitions (PR1). Payload carries from/to/reason and
	// enough field data for the Snapshot reducer to reapply after restart.
	RunStateChanged      = "run.state_changed"
	WaveStateChanged     = "wave.state_changed"
	TaskStateChanged     = "task.state_changed"
	ProcessStateChanged  = "process.state_changed"
	ProtocolStateChanged = "protocol.state_changed"
	ProgressStateChanged = "progress.state_changed"
	TaskRuntimeUpdated   = "task.runtime_updated"
	SupervisorHeartbeat  = "supervisor.heartbeat"
)
